Fix #29
alexlenail/NN-SVG pull request #30
Opened 2019-11-26 16:10 UTC by alexlenail

2019-11-27 09:05 UTC, aFewThings requested changes
With this commits that changed `showConvDims` part on 195 line, you need to modify `showDims` part also :).

2019-11-27 09:05 UTC, aFewThings commented on AlexNet.js
> +                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( convFn(layer['filterHeight'])/2, -3, depthFn(layer['depth'])/2 ) );
I think you need to change like this. Because `height` text should be placed to the right, it needs to use `width` size. 
```suggestion
                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( convFn(layer['filterWidth'])/2, -3, depthFn(layer['depth'])/2 ) );
```

2019-11-27 09:05 UTC, aFewThings commented on AlexNet.js
> +                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( -1, convFn(layer['filterWidth'])/2, depthFn(layer['depth'])/2 ) );
As same reason as above, this line should be changed like this.
```suggestion
                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( -1, convFn(layer['filterHeight'])/2, depthFn(layer['depth'])/2 ) );
```

2019-12-05 17:12 UTC, merged

2019-12-05 17:12 UTC, alexlenail commented
This seems to work, in my quick anecdotal testing.

2019-12-06 09:03 UTC, aFewThings commented
It fixes conv dims, but still has issues in tensor dims. 
https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/AlexNet.js#L186
https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/AlexNet.js#L190